Battle_Control/urls.py
from django.urls import path
from .views import index_view, list_view, create_view, delete_view, detail_view, update_view, battle_view, aplicar_dano, aplicar_cura, aplicar_efeito, inventario_add, inventario_lista, inventario_update, dinheiro_update

app_name = 'rpg'
urlpatterns = [
    path('home/', index_view, name='index'),
    path('criar/', create_view, name='criar'),
    path('listar/', list_view, name='listar'),
    path('detail/<int:pk>', detail_view, name='mostrar'),
    path('atualizar/<int:pk>', update_view, name='atualizar'),
    path('deletar/<int:pk>', delete_view, name='deletar'),
    path('battle/', battle_view, name='batalhar'),
    path('aplicar-dano/', aplicar_dano, name='aplicar_dano'),  # <- Aqui
    path('aplicar-cura/', aplicar_cura, name='aplicar_cura'),
    path("aplicar-efeito/", aplicar_efeito, name="aplicar_efeito"),
    path('inventario/', inventario_lista, name='inventario_lista'),
    path('inventario/add/', inventario_add, name='inventario_add'),
    path('inventario/<int:pk>/update/', inventario_update, name='inventario_update'),
    path('dinheiro/update/', dinheiro_update, name='dinheiro_update'),
]

RPG_Master/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('master/', include('Battle_Control.urls')),
    path('', lambda request: redirect('master/home/')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Battle_Control/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from decimal import Decimal

class Personagem(models.Model):
    Tipo_Personagem = [
        ('Aliado', 'Aliado'),
        ('Inimigo', 'Inimigo'),
    ]

    nome = models.CharField(max_length=20)
    tipo = models.CharField(max_length=10, choices=Tipo_Personagem, default='Aliado')
    level = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(999)])

    vida = models.DecimalField(max_digits=5, decimal_places=1)
    vida_maxima = models.DecimalField(max_digits=5, decimal_places=1)
    defesa = models.DecimalField(max_digits=5, decimal_places=1)
    armadura = models.DecimalField(max_digits=5, decimal_places=1)
    força = models.DecimalField(max_digits=5, decimal_places=1)
    magia = models.DecimalField(max_digits=5, decimal_places=1)
    mana = models.DecimalField(max_digits=5, decimal_places=1)
    agilidade = models.DecimalField(max_digits=5, decimal_places=1)
    resistencia = models.DecimalField(max_digits=5, decimal_places=1)
    necro = models.DecimalField(max_digits=5, decimal_places=1)
    sorte = models.DecimalField(max_digits=5, decimal_places=1)

    barreira_magica = models.PositiveIntegerField(default=0)
    turno = models.IntegerField(default=0)

    imagem = models.ImageField(upload_to='imagens/', null=True, blank=True)

    # Lógica da Armadura e Defesa
    @property
    def defesa_total(self):
        return self.defesa + self.armadura
    def reduzir_armadura(self, valor):
        self.armadura = max(self.armadura - valor, 0)
        self.save()
    def reduzir_defesa_total(self, valor):
        # Reduz apenas a defesa_base, sem afetar a armadura
        nova_defesa = self.defesa_total - valor
        nova_defesa_base = max(nova_defesa - self.armadura, 0)
        self.defesa = nova_defesa_base
        self.save()

    # Lógica da Vida e Resistencia
    def receber_dano(self, dano):
        dano_reduzido = max(dano - self.resistencia, 0)
        self.vida = max(self.vida - dano_reduzido, 0)
        self.save()

    def curar(self, quantidade):
        if not isinstance(quantidade, Decimal):
            quantidade = Decimal(quantidade)
        self.vida += quantidade
        if self.vida_maxima:
            self.vida = min(self.vida, self.vida_maxima)


    def __str__(self):
        return self.nome
    
class Item(models.Model):
    TIPO_ITEM = [
        ('poção', 'Poção'),
    ]
    nome = models.CharField(max_length=50)
    tipo = models.CharField(max_length=10, choices=TIPO_ITEM, default='Poção')
    descricao = models.TextField(blank=True)
    valor_efeito = models.DecimalField(max_digits=5, decimal_places=1, default=0)
    reversivel = models.BooleanField(default=False)
    atributo_afetado = models.CharField(max_length=20, choices=[
        ('vida', 'Vida'),
        ('defesa', 'Defesa'),
        ('armadura', 'Armadura'),
        ('força', 'Força'),
        ('magia', 'Magia'),
        ('mana', 'Mana'),
        ('agilidade', 'Agilidade'),
        ('resistencia', 'Resistência'),
        ('necro', 'Necro'),
        ('sorte', 'Sorte'),
        ('barreira_magica', 'Barreira Mágica')
    ])

    def __str__(self):
        return self.nome
    
class ItemAplicado(models.Model):
    personagem = models.ForeignKey(Personagem, on_delete=models.CASCADE, related_name='itens_aplicados')
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    ativo = models.BooleanField(default=True)
    data_aplicacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.item.nome} em {self.personagem.nome}"

class Inventario(models.Model):
    personagem = models.ForeignKey(Personagem, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.personagem.nome} - {self.item.nome} x{self.quantidade}"
    
class Efeito(models.Model):
    TIPOS = [
        ('buff', 'Buff'),
        ('debuff', 'Debuff'),
        ('habilidade', 'Habilidade'),
        ('arma', 'Arma'),
    ]

    nome = models.CharField(max_length=50)
    tipo = models.CharField(max_length=10, choices=TIPOS)
    reversivel = models.BooleanField(default=True, help_text="Se marcado, o efeito será revertido ao ser removido.")
    modificador_dano = models.IntegerField(default=0)  # positivo ou negativo

    def __str__(self):
        return f"{self.nome} ({self.tipo})"


class EfeitoModificador(models.Model):
    ATRIBUTOS = (
        ('vida', 'Vida'),
        ('defesa', 'Defesa'),
        ('armadura', 'Armadura'),
        ('força', 'Força'),
        ('magia', 'Magia'),
        ('mana', 'Mana'),
        ('agilidade', 'Agilidade'),
        ('resistencia', 'Resistência'),
        ('necro', 'Necro'),
        ('sorte', 'Sorte'),
        ('barreira_magica', 'Barreira Mágica')
    )

    efeito = models.ForeignKey(Efeito, on_delete=models.CASCADE, related_name='modificadores')
    atributo = models.CharField(max_length=20, choices=ATRIBUTOS)
    valor = models.DecimalField(max_digits=5, decimal_places=1)

    def __str__(self):
        return f"{self.atributo} {self.valor:+}"


class EfeitoAplicado(models.Model):
    personagem = models.ForeignKey(Personagem, on_delete=models.CASCADE, related_name='efeitos_aplicados')
    efeito = models.ForeignKey(Efeito, on_delete=models.CASCADE)
    ativo = models.BooleanField(default=True)

    # Armazenar modificações aplicadas, para reversão
    modificacoes_aplicadas = models.JSONField(default=dict)

    def aplicar(self):
        self.modificacoes_aplicadas = {}

        for modificador in self.efeito.modificadores.all():
            atributo = modificador.atributo
            valor = modificador.valor

            if atributo == 'vida':
                # Cura deve respeitar vida_maxima
                self.personagem.curar(valor)
            else:
                original = getattr(self.personagem, atributo)
                setattr(self.personagem, atributo, original + valor)
                self.modificacoes_aplicadas[atributo] = float(valor)

        self.personagem.save()
        self.save()

    def remover(self):
        if self.efeito.reversivel:
            for mod in self.efeito.modificadores.all():
                atributo = mod.atributo
                valor = Decimal(mod.valor)
                atual = getattr(self.personagem, atributo)
                setattr(self.personagem, atributo, atual - valor)
            self.personagem.save()
        self.ativo = False
        self.save()

    def __str__(self):
        return f"{self.efeito.nome} em {self.personagem.nome}"
    
class Dinheiro(models.Model):
    personagem = models.OneToOneField(Personagem, on_delete=models.CASCADE, related_name="dinheiro")
    cobre = models.PositiveIntegerField(default=0)
    prata = models.PositiveIntegerField(default=0)
    ouro = models.PositiveIntegerField(default=0)
    platina = models.PositiveIntegerField(default=0)

    def converter_para_superiores(self):
        # Cobre para prata
        self.prata += self.cobre // 100
        self.cobre = self.cobre % 100

        # Prata para ouro
        self.ouro += self.prata // 100
        self.prata = self.prata % 100

        # Ouro para platina
        self.platina += self.ouro // 100
        self.ouro = self.ouro % 100

        self.save()

Battle_Control/forms.py
from django import forms
from .models import Personagem, Inventario

class PersonagemForm(forms.ModelForm):
    class Meta:
        model = Personagem
        fields = ['nome',  'tipo', 'level', 'vida', 'defesa', 'força', 'magia', 'mana', 'agilidade', 'resistencia', 'necro', 'sorte', 'imagem'] # Controla a ordem das coisas
        labels = {
            'nome': 'Nome',
            'tipo': 'Tipo',
            'level': 'Level',
            'vida': 'Vida',
            'defesa': 'Defesa',
            'força': 'Força',
            'magia': 'Magia',
            'mana': 'Mana',
            'agilidade': 'Agilidade',
            'resistencia': 'Resistencia',
            'necro': 'Necro',
            'sorte': 'Sorte',
            'imagem': 'Imagem',
        }
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo': forms.Select(attrs={'class': 'form-control'}),
            'level': forms.NumberInput(attrs={'class': 'form-number'}),
            'vida': forms.NumberInput(attrs={'class': 'form-number'}),
            'defesa': forms.NumberInput(attrs={'class': 'form-number'}),
            'força': forms.NumberInput(attrs={'class': 'form-number'}),
            'magia': forms.NumberInput(attrs={'class': 'form-number'}),
            'mana': forms.NumberInput(attrs={'class': 'form-number'}),
            'agilidade': forms.NumberInput(attrs={'class': 'form-number'}),
            'resistencia': forms.NumberInput(attrs={'class': 'form-number'}),
            'necro': forms.NumberInput(attrs={'class': 'form-number'}),
            'sorte': forms.NumberInput(attrs={'class': 'form-number'}),
            'imagem': forms.FileInput(attrs={'class': 'form-button'}),
        }

class InventarioForm(forms.ModelForm):
    class Meta:
        model = Inventario
        fields = ['personagem', 'item', 'quantidade']
        widgets = {
            'personagem': forms.HiddenInput(),
            'item': forms.Select(attrs={'class': 'form-select'}),
            'quantidade': forms.NumberInput(attrs={'class': 'form-input', 'min': 1}),
        }
        
class DinheiroForm(forms.Form):
    MOEDAS = [
        ('cobre', 'Cobre'),
        ('prata', 'Prata'),
        ('ouro', 'Ouro'),
        ('platina', 'Platina'),
    ]
    moeda = forms.ChoiceField(choices=MOEDAS)
    valor = forms.IntegerField(min_value=1, max_value=100)
    acao = forms.ChoiceField(choices=[('add', 'Adicionar'), ('sub', 'Remover')])

Battle_Control/templates/site/atualizar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alterar</title>
    <style>
        body {
            background-color: #18191C;
            text-align: center;
            color: white;
            font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
        }
        .link {
            font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
            background-color: white; /* cor de fundo escura */
            color: #18191C;               /* cor da letra */
            text-decoration: none;      /* tira sublinhado */
            border: none;               /* tira borda */
            padding: 10px 20px;
            border-radius: 5px;
            display: inline-block;
            cursor: pointer;
            transition: 0.2s;
        }
        .link:hover {                   /* quando mouse passa por cima */
            background-color: white;  /* Muda a cor */
            transform: scale(1.03);     /* aumenta o tamanho */
        }
        .link:active {              /* quando clica e segura */
            transform: scale(0.98); /* O quão diminui */
        }
        
        .form {
            color: white;
            font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
        }
        .form-number {
            font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
            width: 70px;
            text-align: center;
            height: 25px;
            border-radius: 5px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
            outline: none;
            transition: border-color 0.3s ease, box-shadow 0.3s ease;;
            font-size: 15px;
        }
        .form-control {
            font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
            width: 170px;
            text-align: center;
            height: 25px;
            border-radius: 5px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
            outline: none;
            transition: border-color 0.3s ease, box-shadow 0.3s ease;;
            font-size: 15px;
        }
        .form-control:focus, .form-number:focus{
            border-color: white;
            box-shadow: 0 0 20px 5px rgba(255, 255, 255, 0.5);
        }
        .form-button {
            font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
            background-color: white; /* cor de fundo escura */
            color: #18191C;               /* cor da letra */
            text-decoration: none;      /* tira sublinhado */
            border: none;               /* tira borda */
            padding: 10px 20px;
            border-radius: 5px;
            display: inline-block;
            cursor: pointer;
            transition: 0.2s;
        }
    </style>
</head>
<body>
    <h2>Alterar ficha de {{ personagem.nome }}</h2>
    <form class="form" action="{% url 'rpg:atualizar' personagem.id %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <br>
            {{ field.label_tag }}
            
            {{ field }}
            <br>
        {% endfor %}
        <br>
        <button class="link" type="submit">Alterar</button>
    </form><br>
    <a class="link" href="{% url 'rpg:listar' %}">Voltar</a>
</body>
</html>

Battle_Control/templates/site/criar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criação de Personagem</title>
    <style>
        body {
            background-color: #18191C;
            text-align: center;
        }
        h2 {
            color: white;
            font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
        }
        .link {
            font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
            background-color: white; /* cor de fundo escura */
            color: #18191C;               /* cor da letra */
            text-decoration: none;      /* tira sublinhado */
            border: none;               /* tira borda */
            padding: 10px 20px;
            border-radius: 5px;
            display: inline-block;
            cursor: pointer;
            transition: 0.2s;
        }
        .link:hover {                   /* quando mouse passa por cima */
            background-color: white;  /* Muda a cor */
            transform: scale(1.03);     /* aumenta o tamanho */
        }
        .link:active {              /* quando clica e segura */
            transform: scale(0.98); /* O quão diminui */
        }
        
        .form {
            color: white;
            font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
        }
        .form-number {
            font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
            width: 70px;
            text-align: center;
            height: 25px;
            border-radius: 5px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
            outline: none;
            transition: border-color 0.3s ease, box-shadow 0.3s ease;;
            font-size: 15px;
        }
        .form-control {
            font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
            width: 170px;
            text-align: center;
            height: 25px;
            border-radius: 5px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
            outline: none;
            transition: border-color 0.3s ease, box-shadow 0.3s ease;;
            font-size: 15px;
        }
        .form-control:focus, .form-number:focus{
            border-color: white;
            box-shadow: 0 0 20px 5px rgba(255, 255, 255, 0.5);
        }
        .form-button {
            font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
            background-color: white; /* cor de fundo escura */
            color: #18191C;               /* cor da letra */
            text-decoration: none;      /* tira sublinhado */
            border: none;               /* tira borda */
            padding: 10px 20px;
            border-radius: 5px;
            display: inline-block;
            cursor: pointer;
            transition: 0.2s;
        }
    </style>
</head>
<body>
    <h2>Criação de Personagem</h2>
    <form class="form" action="{% url 'rpg:criar' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <br>
            {{ field.label_tag }}
            
            {{ field }}
            <br>
        {% endfor %}
        <br>
        <button class="link" type="submit">Criar</button>
    </form><br>
    <a class="link" href="{% url 'rpg:index' %}">Voltar</a>     <a href="{% url 'rpg:listar' %}" class="link">Personagens Criados</a><br><br>
</body>
</html>

Battle_Control/templates/site/detalhes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ personagem.nome }}</title>
    <style>
        body {
            background-color: #18191C;
            text-align: center;
            color: white;
            font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
        }
        .link {
            background-color: white; /* cor de fundo escura */
            color: #18191C;               /* cor da letra */
            text-decoration: none;      /* tira sublinhado */
            border: none;               /* tira borda */
            padding: 10px 20px;
            border-radius: 5px;
            display: inline-block;
            cursor: pointer;
            transition: 0.2s;
        }

        .link:hover {
            background-color: white;
            transform: scale(1.03);
        }

        .link:active {
            transform: scale(0.98);
        }
        div {
            background-color: white; /* cor de fundo escura */
            color: #18191C;               /* cor da letra */
            padding: 10px 50px; /* altura e largura */
            border-radius: 15px;
            display: inline-block;
            cursor: default;
            transition: 0.2s;
        }
    </style>
</head>
<body>
    <h2>Ficha de {{ personagem.nome }}</h2>
    <div>
        <b><p>Nome: {{ personagem.nome }} | Lvl {{ personagem.level }}</p>
        <p>Tipo: {{ personagem.tipo }}</p></b>
        <br>
        <p><b>Vida:</b> {{ personagem.vida|floatformat:"-2" }}</p>
        <p><b>Defesa:</b> {{ personagem.defesa|floatformat:"-2" }}</p>
        <p><b>Força:</b> {{ personagem.força|floatformat:"-2" }}</p>
        <p><b>Magia:</b> {{ personagem.magia|floatformat:"-2" }}</p>
        <p><b>Mana:</b> {{ personagem.mana|floatformat:"-2" }}</p>
        <p><b>Agilidade:</b> {{ personagem.agilidade|floatformat:"-2" }}</p>
        <p><b>Resistencia:</b> {{ personagem.resistencia|floatformat:"-2" }}</p>
        <p><b>Necro:</b> {{ personagem.necro|floatformat:"-2" }}</p>
        <p><b>Sorte:</b> {{ personagem.sorte|floatformat:"-2" }}</p>
        <P>{{ personagem.imagem }}</p>
    </div>
    <br><br><a class="link" href="{% url 'rpg:listar' %}">Voltar</a>
</body>
</html>

Battle_Control/templates/site/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RPG MANAGER</title>
    <style>
        body {
            background-color: #18191C;
            text-align: center;
            color: white;
            font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
        }
        .link {
            background-color: white; /* cor de fundo escura */
            color: #18191C;               /* cor da letra */
            text-decoration: none;      /* tira sublinhado */
            border: none;               /* tira borda */
            padding: 10px 20px;
            border-radius: 5px;
            display: inline-block;
            cursor: pointer;
            transition: 0.2s;
        }

        .link:hover {
            background-color: white;
            transform: scale(1.03);
        }

        .link:active {
            transform: scale(0.98);
        }
    </style>
</head>
<body>
    <body>
        <h2>Brittania Fallen RPG Battle</h2>
        <a href="{% url 'rpg:listar' %}" class="link">Personagens</a>
        <a href="{% url 'rpg:criar' %}" class="link">Criar Novo</a>
        <a href="{% url 'rpg:batalhar' %}" class="link">Batalhar</a>
        <a href="{% url 'rpg:inventario_lista' %}" class="link">Inventario</a>
        <hr>
        <br>
    </body>
</body>
</html>

Battle_Control/templates/site/inventario_lista.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Planejamento</title>
    <link rel="stylesheet" href="{% static 'Battle_Control/css/adventure.css' %}?v=2">
</head>
<body>
{% with carteira=personagens.0.dinheiro %}
<div>
  <h2>Carteira Compartilhada</h2>
  <p>
    💰 Cobre: <strong>{{ carteira.cobre }}</strong> |
    🪙 Prata: <strong>{{ carteira.prata }}</strong> |
    🧈 Ouro: <strong>{{ carteira.ouro }}</strong> |
    👑 Platina: <strong>{{ carteira.platina }}</strong>
  </p>
  <form method="POST" action="{% url 'rpg:dinheiro_update' %}">
    {% csrf_token %}
    <select name="moeda" class="border p-1 rounded">
      <option value="cobre">Cobre</option>
      <option value="prata">Prata</option>
      <option value="ouro">Ouro</option>
      <option value="platina">Platina</option>
    </select>
    <input type="number" name="valor" min="1" max="100" required>
    <button type="submit" name="acao" value="sub">−</button>
    <button type="submit" name="acao" value="add">+</button>
  </form>
</div>
{% endwith %}

<br><br>
<div class="personagens-container">
  <div class="cards-container">
    {% for p in personagens %}
      <div class="card">
        <h2>{{ p.nome }} - Lv {{ p.level }}</h2>
        {% if p.imagem %}
          <img src="{{ p.imagem.url }}" width="100" class="imagem-personagem">
        {% else %}
          <em>Sem imagem</em>
        {% endif %}<br><br>

        {% for inv in p.inventario_set.all %}
        <div>
          <div>
            <strong>{{ inv.item.nome }}</strong> x{{ inv.quantidade }}
          </div>
          <div>
            <form method="POST" action="{% url 'rpg:inventario_update' inv.pk %}" style="display:inline;">
              {% csrf_token %}
              <input type="hidden" name="action" value="decrement">
              <button type="submit" class="px-2 py-1 bg-red-500 text-white rounded">−</button>
            </form>
            <form method="POST" action="{% url 'rpg:inventario_update' inv.pk %}" style="display:inline;">
              {% csrf_token %}
              <input type="hidden" name="action" value="increment">
              <button type="submit" class="px-2 py-1 bg-green-500 text-white rounded">+</button>
            </form>
          </div>
        </div>
        {% empty %}
        <p>Nenhum item.</p>
        {% endfor %}

        <form method="POST" action="{% url 'rpg:inventario_add' %}" class="mt-3">
          {% csrf_token %}
          {{ novo_form.as_p }}
          <input type="hidden" name="personagem" value="{{ p.pk }}">
          <button type="submit" class="mt-2 px-3 py-1 bg-blue-600 text-white rounded">
            Adicionar Item
          </button>
        </form>
      </div>
    {% endfor %}
  </div>
</div>

<hr>
<a class="link" href="{% url 'rpg:batalhar' %}">Ir para Batalha</a>
<a class='link'href="{% url 'rpg:index' %}">Início</a>
</body>
</html>

Battle_Control/templates/site/listar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Personagens</title>
    <style>
        body {
            background-color: #18191C;
            text-align: center;
            color: white;
            font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
            cursor: default;
        }
        table {
            margin: 0 auto;
            width: 50%; /* espaçamento entre verticais */
            border-collapse: collapse;
        }
        th, td {
            border-bottom: 1px solid #ccc;
            padding: 12px 16px; /* espaçamento externo dos elementos */
            text-align: center;
        }
        th {
            border-bottom: 2px solid #888;
        }
        .link {
            background-color: white; /* cor de fundo escura */
            color: #18191C;               /* cor da letra */
            text-decoration: none;      /* tira sublinhado */
            border: none;               /* tira borda */
            padding: 10px 20px;
            border-radius: 5px;
            display: inline-block;
            cursor: pointer;
            transition: 0.2s;
        }
        .link:hover {
            background-color: white;
            transform: scale(1.03);
        }

        .link:active {
            transform: scale(0.98);
        }
    </style>
</head>
<body>
    {% if personagens %}
        <h2>Personagens</h2>
        <table>
            <tr>
                <th>Nome</th>
                <th>Tipo</th>
                <th>Opções</th>
            </tr>
            {% for personagem in personagens %}
                <tr>
                    <td>{{ personagem.nome }}</td>
                    <td>{{ personagem.tipo }}</td>
                    <td>
                        <a class="link" href="{% url 'rpg:mostrar' personagem.id %}">Acessar ficha</a>
                        <a class="link" href="{% url 'rpg:atualizar' personagem.id %}">Atualizar</a>
                        <a class="link" href="{% url 'rpg:deletar' personagem.id %}" onclick="return confirm('Tem certeza disso?')">Deletar</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <br>
        <a class="link" href="{% url 'rpg:index' %}">Voltar</a>
        <a class="link" href="{% url 'rpg:criar' %}" class="link">Criar Novo</a><br>
    {% else %}
        <h2>Sem personagens criados</h2>
        <a class="link" href="{% url 'rpg:criar' %}">Criar Novo</a>
        <a class="link" href="{% url 'rpg:index' %}">Voltar</a>
    {% endif %}
</body>
</html>